package(default_visibility = ["//visibility:public"])

licenses(["notice"])

filegroup(
    name = "distribution",
    srcs = glob([
        "**",
    ]),
    visibility = [
        "@//distro:__pkg__",
    ],
)