name: main

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          bazelisk build //...