name: main

on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v1

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: $HOME/.cache/bazel
          key: bazel-${{ matrix.os }}

      - name: Build
        run: |
          bazelisk --output_user_root="${HOME}/.cache/bazel" build //...